#!/bin/bash

###############################################################################
# Cron Setup Helper for GitHub Copilot Sync System
# 
# Helps set up automatic syncing via cron
###############################################################################

WORKSPACE_DIR="$HOME/.openclaw/workspace"
CRON_FILE="/tmp/openclaw-copilot-cron"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}GitHub Copilot Sync - Cron Setup${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# Create cron entries
cat > "$CRON_FILE" << 'EOF'
# GitHub Copilot Account Sync System
# Auto-generated by setup-cron.sh

# Sync accounts every 4 hours
0 */4 * * * cd ~/.openclaw/workspace && node github-copilot-sync.js sync --quiet >> logs/sync-cron.log 2>&1

# Monitor and alert every 2 hours
0 */2 * * * cd ~/.openclaw/workspace && node github-copilot-sync.js monitor >> logs/monitor-cron.log 2>&1

# Daily health check at 9 AM
0 9 * * * cd ~/.openclaw/workspace && node github-copilot-sync.js status >> logs/status-daily.log 2>&1

EOF

echo "Proposed cron entries:"
echo ""
cat "$CRON_FILE" | grep -v "^#" | grep -v "^$"
echo ""
echo -e "${YELLOW}Note: This will sync every 4 hours and monitor every 2 hours${NC}"
echo ""

# Ask for confirmation
read -p "Add these cron jobs? (y/n) " -n 1 -r
echo ""

if [[ $REPLY =~ ^[Yy]$ ]]; then
    # Create logs directory
    mkdir -p "$WORKSPACE_DIR/logs"
    
    # Add to crontab
    (crontab -l 2>/dev/null; cat "$CRON_FILE") | crontab -
    
    echo -e "${GREEN}✓ Cron jobs added successfully!${NC}"
    echo ""
    echo "View your crontab with: crontab -l"
    echo "Remove with: crontab -e (then delete the lines)"
    echo ""
    echo "Log files will be in: $WORKSPACE_DIR/logs/"
else
    echo "Cancelled. You can manually add these entries with: crontab -e"
fi

rm -f "$CRON_FILE"

echo ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}Alternative: Use the daemon instead${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "Instead of cron, you can run the daemon:"
echo "  ./sync-daemon.sh start"
echo ""
echo "The daemon is easier to manage and provides better logging."
echo ""
